config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/new'
  get 'users/create'
  root to: 'home#home'
  get 'reg', to:'home#reg'
  post 'create', to:'home#create'
  get 'pregame', to:'game#pregame'
  get 'game', to:'game#game'
  post 'game_create', to:'game#game_create'
  resources :employees, only: [:index, :show]
  post 'game/check/:min/:sec' , to:'game#time'
  get 'start5', to:'game#start5'
  get 'game/getplayerInfo/:id', to:'game#player_info'
  post 'game/start5_confirm/:p1id/:p2id/:p3id/:p4id/:p5id', to:'game#start5_confirm'
  post 'game/finish/:score/:opp_score', to:'game#finish'
  post 'game/stuts_record/:p_id/:p_name/:playing_time/:a/:b/:c/:d/:e/:f/:g/:h/:i/:j/:k/:l/:m', to:'game#stuts_record'
  get 'home/box', to:'home#box'
  get 'home/player_select', to:'home#player_select'
  get 'home/player_edit', to:'home#player_edit'
  patch 'home/player_update' , to:'home#player_update'
  patch 'home/player_delete', to:'home#player_delete'
  resources :users, only: [:new, :create]
  get "/login" => "sessions#new"
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :teams do
    member do
      get 'details'
    end
    collection do
      get 'search'
    end
    resources :players
  end
  
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  protect_from_forgery 
  skip_before_action :verify_authenticity_token
  before_action :team_presence, only: [:pregame]
  def pregame
    teams
    @game_setting = Game.new
  end
  
  def game_create
    @game_setting = Game.new(game_params)
    @game_setting.save
    redirect_to start5_path
  end
  
  def start5
    @team = Game.last
    @players = Player.where(team_id: @team.team)
    sleep(0.5)
    
  end
  
  def player_info
    @player = Player.find(params[:id])
    render json: @player
  end
  
  def time
    @game = Game.last
    @min = params[:min]
    @sec = params[:sec]
    @game.min = @min
    @game.sec = @sec
    if @game.save
    else
      @game.update
    end
  end
  
  
  
  def start5_confirm
    @start5 = Start5.new
    @start5.team = Game.last.team
    @start5.p1 = Player.find(params[:p1id]).id
    @start5.p2 = Player.find(params[:p2id]).id
    @start5.p3 = Player.find(params[:p3id]).id
    @start5.p4 = Player.find(params[:p4id]).id
    @start5.p5 = Player.find(params[:p5id]).id
    @start5.save
  end
  
  def game
    sleep(0.1)
    @game = Game.last
    @period = @game.period_time
    s = Start5.last
    start5players_id = [s.p1,s.p2,s.p3,s.p4,s.p5]
    period_time_allsecond = @period.to_i * 60
    start5players_id.each do |s|
      start5player = Changeplayer.new(inplayer: s, clock: period_time_allsecond , game_id: @game.id)
      start5player.save
    end
    @start5players = Array.new
    @players = Player.where(team_id: @game.team)
    start5players_id.each do |pid|
      player =  @players.find(pid)
      @start5players.push(player)
    end
    @reserves = @players.where.not(id: @start5players_id)
  end
  
  def finish
    game = Game.last
    game.score = params[:score].to_i
    game.opp_score = params[:opp_score].to_i
    game.save
  end
  
  def stuts_record
    game = Game.last
    Stut.new(player_id: params[:p_id], player_name: params[:p_name], game_id: game.id, team_id: game.team, 
             playingtime: params[:playing_time].to_i,FGmake: params[:a].to_i + params[:c].to_i,
             FGmiss: params[:b].to_i + params[:d].to_i, Deepmake: params[:c].to_i, Deepmiss: params[:d].to_i, FTmake: params[:e].to_i,
             FTmiss: params[:f].to_i, DefReb: params[:g].to_i, OffReb: params[:h].to_i, Assist: params[:i].to_i,
             Block: params[:j].to_i, steal: params[:k].to_i, TO: params[:l].to_i, PF: params[:m].to_i, 
             point: params[:a].to_i * 2 + params[:c].to_i * 3 +  params[:e].to_i).save
  end
  
  def plays_array
    @play_kinds = ["FGmake","FGmiss","Deepmake","Deepmiss","FTmake","FTmiss","DefReb",
                   "OffReb","Assist","Block","steal","TO","PF"]
  end
  
  
  
  private
    def game_params
      params.require(:game).permit(:team, :period_time,:opp_name)
    end
    
    def start5_params
      params.require(:start5).permit(:team,:p1,:p2,:p3,:p4,:p5)
    end
    
    def team_presence
      if Team.last.nil?
        flash[:warning] = "チームを登録してください"
        redirect_to team_reg_path
      end
    end
  
  
end
 

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/game.html.slim
#game.mx-3
  div
  h2 v-text="formatTime" 
  button v-on:click="start" v-if="!timerOn" Start
  button v-on:click="stop" v-if="timerOn" Stop
  br
  a.h5 v-text = "quater"
  a.h5 Q    
  a.h5 v-text="score"
  a  - 
  a.h5 v-text="opp_score"
  br
  a 得点調整（味方は自動的に入ります）
  br
  a 味方
  button v-on:click = "score_plus" +
  button.mr-2 v-on:click = "score_minus" -
  a 敵
  button v-on:click = "opp_score_plus" +
  button v-on:click = "opp_score_minus" -
  
  div v-if = "playerChangebool == false"
    a 出場中の選手(クリックでスコア)
    br
    button.m-1 v-for="oncourtplayer in oncourt" v-on:click="scorings(oncourtplayer.id)" v-text = "oncourtplayer.name"

  button.m-1 v-if = "Scoringbool == false" v-on:click = "playerChangebtn" 選手交代
    
  div v-show="Scoringbool"
    a プレイヤー名：
    a v-text="playing_player.name"
    br
    button.m-1 v-for="(play,index) in plays"  v-on:click="Play(index)"  v-text = "play.kinds"
    
    
  div v-show = "playerChangebool"
    a 入る選手 
    br
    button.m-1 v-for="reserve in bench" v-on:click = "inPlayerbtn(reserve.id)" v-text = "reserve.name"
  
  div v-show = "outPlayerbool"
    a 下がる選手
    br
    button.m-1 v-for="oncourtplayer in oncourt" v-on:click = "outPlayerbtn(oncourtplayer.id)" v-text = "oncourtplayer.name"
  
  div v-show = "Cancellbool"
    button.mt-1 v-on:click = "Cancell" キャンセル
    
  div
    p プレー履歴（クリックでキャンセル）
    a[v-for="(record,index) in play_record" v-if="index <= 4" v-on:click = "play_delete(index)"]
      button.mb-1
        | {{index + 1}} {{record.player_name}}  {{record.play}} 
      br
      
  div.text-right.mr-4
    button v-on:click="nextquater" 次のクォーターへ
    button v-on:click="finish" = link_to "試合終了", home_box_path(:game_id => @game.id)
a type="text" id="min"  class="d-none" = @period
- @start5players.each do |s5p|
  a type="text" id = s5p.id  class="start5player"


- @players.each do |p|
 a type="text"  id = p.id class="d-none players" 



= javascript_pack_tag "game/game"

app/views/game/pregame.html.slim
#pregame
  = form_with(model: @game_setting, url:game_create_path, local:true) do |f|
    ul.m-2
      li.m-2
        = f.label :チーム名, class: 'mr-2'
        = f.collection_select(:team, @teams, :id, :team_name)
        br
        = f.label :相手チーム名, class: 'mr-2'
        = f.text_field :opp_name
      li.m-2
        = f.label :'1ピリオドの時間(分)', class: 'mr-2'
        = f.text_field(:period_time, readonly: true,"v-model.number": "period_time")
        button　type="button" @click="plus" +
        button type="button" @click="minus" -
      = f.submit 'スタメン選択', class: 'btn btn-primary' 
= javascript_pack_tag "game/pregame"

app/views/game/start5.html.slim
div.mx-4  
  #start5
    p スタメンを選んでください
    a.mb-2 [v-for = 'player in not_chosen_players' v-on:click = 'set_start5(player.id,player.name,player.position)']
      button.m-1
        |  {{player.name}}
         
    
    h5.mb-1 スタメン
    
    p [v-for = 'player in start5Array']
      a.mb-2
        |  {{player.name}} : {{player.position}}
        button.ml-1  v-on:click = 'cancell(player.id,player.name,player.position)' キャンセル
        br
    button.ml-3  v-show= 'occupied' v-on:click = 'start5Confirm' = link_to "試合へ" , game_path 
    
    
  - @players.each do |p|
    a type="text"  id = p.id class="d-none players"
= javascript_pack_tag "game/start5"