config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/new'
  get 'users/create'
  root to: 'home#home'
  get 'reg', to:'home#reg'
  post 'create', to:'home#create'
  get 'pregame', to:'game#pregame'
  get 'game', to:'game#game'
  post 'game_create', to:'game#game_create'
  resources :employees, only: [:index, :show]
  post 'game/check/:min/:sec' , to:'game#time'
  get 'start5', to:'game#start5'
  get 'game/getplayerInfo/:id', to:'game#player_info'
  post 'game/start5_confirm/:p1id/:p2id/:p3id/:p4id/:p5id', to:'game#start5_confirm'
  post 'game/finish/:score/:opp_score', to:'game#finish'
  post 'game/stuts_record/:p_id/:p_name/:playing_time/:a/:b/:c/:d/:e/:f/:g/:h/:i/:j/:k/:l/:m', to:'game#stuts_record'
  get 'home/box', to:'home#box'
  get 'home/player_select', to:'home#player_select'
  get 'home/player_edit', to:'home#player_edit'
  patch 'home/player_update' , to:'home#player_update'
  patch 'home/player_delete', to:'home#player_delete'
  resources :users, only: [:new, :create]
  get "/login" => "sessions#new"
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :teams do
    member do
      get 'details'
    end
    collection do
      get 'search'
    end
    resources :players
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  
  
  
  def home
    if current_user
      teams
    end
  end
  
  
  
  
  
  
  
 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  def box
    @game = Game.last
    @players = Player.where(team_id: @game.team)
    @team = Team.find(@game.team)
    @player_stuts_array = []
    @players.each do |p|
      @stuts = Stut.find_by(player_id: p.id, game_id: @game.id)
      box_stuts
      stuts_array = [p.name,p.position,@mts,@pts,@reb,@oreb,@dreb,@ast,@stl,
                     @blk,@fgm,@fga,"#{@fgp}%",@dpm,@dpa,"#{@dpp}%",@ftm,@fta,"#{@ftp}%",
                     @tov,@pf].map(&:to_s)
      @player_stuts_array.push(stuts_array)
    end
  end
  
  
  
  private
  
    
    
    
    
    
    
    
    
    def team_presence
      if Team.last.nil?
        flash[:warning] = "チームを登録してください"
        redirect_to team_reg_path
      end
    end
    
    def box_stuts
      while @stuts.nil? do
        sleep(0.1)
      end
      @mts = @stuts.playingtime.fdiv(60).round(1)
      @pts = @stuts.point
      @oreb = @stuts.OffReb
      @dreb = @stuts.DefReb
      @reb = @oreb + @dreb
      @ast = @stuts.Assist
      @stl = @stuts.steal
      @blk = @stuts.Block
      @fgm = @stuts.FGmake
      @fga = @fgm + @stuts.FGmiss
      get_shot_percent
      @tov = @stuts.TO
      @pf = @stuts.PF
    end
    
    def get_shot_percent
      if  @fga == 0
        @fgp = 0
      else
        @fgp = @fgm.fdiv(@fga).round(3) * 100
      end
      @dpm = @stuts.Deepmake
      @dpa = @dpm + @stuts.Deepmiss
      if @dpa == 0
        @dpp = 0
      else
        @dpp = @dpm.fdiv(@dpa).round(3) * 100
      end
      @ftm = @stuts.FTmake
      @fta = @ftm + @stuts.FTmiss
      if @fta == 0
        @ftp = 0
      else
        @ftp =  @ftm.fdiv(@fta).round(3) * 100
      end
    end
    
    
    
    
end

app/helpers/home_helper.rb
module HomeHelper
  def box_stuts
    while @stuts.nil? do
      sleep(0.1)
    end
    @mts = @stuts.playingtime.fdiv(60).round(1)
    @pts = @stuts.point
    @oreb = @stuts.OffReb
    @dreb = @stuts.DefReb
    @reb = @oreb + @dreb
    @ast = @stuts.Assist
    @stl = @stuts.steal
    @blk = @stuts.Block
    @fgm = @stuts.FGmake
    @fga = @fgm + @stuts.FGmiss
    if  @fga == 0
      @fgp = 0
    else
      @fgp = @fgm.fdiv(@fga).round(3) * 100
    end
    @dpm = @stuts.Deepmake
    @dpa = @dpm + @stuts.Deepmiss
    if @dpa == 0
      @dpp = 0
    else
      @dpp = @dpm.fdiv(@dpa).round(3) * 100
    end
    @ftm = @stuts.FTmake
    @fta = @ftm + @stuts.FTmiss
    if @fta == 0
      @ftp = 0
    else
      @ftp =  @ftm.fdiv(@fta).round(3) * 100
    end
    @tov = @stuts.TO
    @pf = @stuts.PF
  end
  
  
  def simple_stuts
    @mpg = @stuts.sum(:playingtime).fdiv(@play_times).fdiv(60).round(1)
    @ppg = @stuts.sum(:point).fdiv(@play_times).round(1)
    @reb = @stuts.sum(:DefReb) + @stuts.sum(:OffReb)
    @rpg = @reb.fdiv(@play_times).round(1)
    @apg = @stuts.sum(:Assist).fdiv(@play_times).round(1)
    @fg_all = @stuts.sum(:FGmake) + @stuts.sum(:FGmiss)
    if  @fg_all == 0
      @fgp = 0
    else
      @fgp = (100 * @stuts.sum(:FGmake)).fdiv(@fg_all).round(1) 
    end
    @deep_all = @stuts.sum(:Deepmake) + @stuts.sum(:Deepmiss)
    if @deep_all == 0
      @dpp = 0
    else
      @dpp = (100 * @stuts.sum(:Deepmake)).fdiv(@deep_all).round(1) 
    end
    @ft_all= @stuts.sum(:FTmake) + @stuts.sum(:FTmiss)
    if @ft_all == 0
      @ftp = 0
    else
      @ftp =  (100 * @stuts.sum(:FTmake)).fdiv(@ft_all).round(1) 
    end
  end
  
  def detail_stuts
    @orpg = @stuts.sum(:OffReb).fdiv(@play_times).round(1)
    @drpg = @stuts.sum(:DefReb).fdiv(@play_times).round(1)
    @spg = @stuts.sum(:steal).fdiv(@play_times).round(1)
    @bpg = @stuts.sum(:Block).fdiv(@play_times).round(1)
    @fga = @fg_all.fdiv(@play_times).round(1)
    @fgm = @stuts.sum(:FGmake).fdiv(@play_times).round(1)
    @dpa = @deep_all.fdiv(@play_times).round(1)
    @dpm = @stuts.sum(:Deepmake).fdiv(@play_times).round(1)
    @fta = @ft_all.fdiv(@play_times).round(1)
    @ftm = @stuts.sum(:FTmake).fdiv(@play_times).round(1)
    @topg = @stuts.sum(:TO).fdiv(@play_times).round(1)
  end
end

app/views/home/box.html.slim
div.mx-3  
  h2   ボックススコア
  div.table-responsive
      table.table.table-hover.text-nowrap
        thead
          tr
            th  名前
            th  ポジション
            th MIN
            th PTS
            th REB
            th OREB
            th DREB
            th AST
            th STL
            th BLK
            th FGM
            th FGA
            th FG%
            th 3PM
            th 3PA
            th 3P%
            th FTM
            th FTA          
            th FT%
            th TOV
            th PF
        
        tbody
          - @player_stuts_array.each do |stuts_array|
            tr
              - stuts_array.each do |s|
                td = s
              
  div
    p.text-right = link_to "チームページへ" , team_page_path(:id => @team.id)

app/views/home/home.html.slim
#hello.mx-4
  .container-fluid
    .row
      - if current_user
        .col-lg-6.col-sm-12
          h3.text-center 登録チーム
          .m-3
            - @teams.each do |t|
              .container.p-4.border.mb-1
                = link_to(team_path(id: t.id)) do
                  = t.team_name
                br
        
      .col-lg-6.col-sm-12
        h3.text-center チーム検索
        .m-3
          = form_with(url:search_teams_path,method: :get,local:true) do |f| 
            p
              a = f.label :チーム名, class: 'mr-2'
              a.ml-3 = f.text_field :team_name
            
            = f.submit '検索', class: 'btn btn-primary ml-5', name: nil 
    
  
= javascript_pack_tag "home"

app/views/home/player_edit.html.slim
div.container-fluid.m-4
  .row
    .col-sm-6.col-lg-3
      p 元の選手名,ポジション
      p  = "#{@player.name} : #{@player.position}"
      
    .col-sm-6.col-lg-3
      p  新しい選手名,ポジション
      = form_with(model: @player, url:home_player_update_path(id:@player.id), local:true) do |f|
        = f.text_field :name
        = f.select :position, {'ガード': 'G', 'フォワード': 'F', 'センター': 'C', 'G/F': 'G/F', 'F/C': 'F/C'} 
        = f.submit '変更', class: 'btn btn-primary mt-2' 
    
    .col-sm-6.col-lg-3
      = form_with(model: @player, url:home_player_delete_path(id:@player.id), local:true) do |f|
        = f.submit '選手削除', class: 'btn btn-danger mt-2' 

app/views/home/reg.html.slim
#reg.mx-4
  h2.ml-5 選手登録
  = form_with(model: @player, url:create_path, local:true) do |f|
    
    p
      a = f.label :名前, class: 'mr-2'
      a.ml-3 = f.text_field :name
    p
      a = f.label :ポジション
      a = f.select :position, {'ガード': 'G', 'フォワード': 'F', 'センター': 'C', 'G/F': 'G/F', 'F/C': 'F/C'} 
    
    p
      a = f.label :チーム
      a.ml-5 = f.collection_select(:team_id, @teams, :id, :team_name) 
    = f.submit '選手登録', class: 'btn btn-primary ml-5' 
      
      
      
= javascript_pack_tag "home"

app/views/home/team_edit.html.slim
div.container-fluid.m-4
  .row
    .col-sm-6.col-lg-3
      p 元のチーム名
      p  = @team.team_name
      
    .col-sm-6.col-lg-3
      p  新しいチーム名
      = form_with(model: @team, url:home_team_update_path(id:@team.id), local:true) do |f|
        = f.text_field :team_name
        = f.submit 'チーム名変更', class: 'btn btn-primary mt-2' 
    
    .col-sm-6.col-lg-3
      = form_with(model: @team, url:home_team_delete_path(id:@team.id), local:true) do |f|
        = f.submit 'チーム削除', class: 'btn btn-danger mt-2' 

app/views/home/team_page.html.slim
div#team_page.mx-4
  h2 = @team_name
  - if current_user
    - if current_user.id.to_s == @team.user_id
      a = link_to "チーム編集",home_team_edit_path(id: @team.id) 
      a.ml-3 = link_to "選手編集",home_player_select_path(id: @team.id) 
  div
    h3 チーム成績
    h5 = "#{@win}勝#{@lose}負#{@draw}引"
    h5 直近5試合
    - @games.each do |g|
      a = "#{g.score} - #{g.opp_score}  対 #{g.opp_name}"
      br
  div
    h4 個人成績（名前クリックで詳細スタッツ）
  div.table-responsive-sm
    table.table.table-hover.text-nowrap
      thead
        tr
          th  名前
          th  ポジション
          th  MPG
          th  PPG
          th  RPG
          th  APG
          th  FG%
          th  3P%
          th  FT%
      
      tbody
        - @player_stuts_array.zip(@players).each do |stuts_array,p|
          tr
            td v-on:click="get_details(#{p.id})" 
              = p.name
            - stuts_array.each do |s|
              td = s
  
  div.table-responsive-xl v-show ="detailsbool"
    table.table.table-hover.text-nowrap
      thead
        tr
          th 名前
          th MPG
          th PPG
          th RPG
          th ORPG
          th DRPG
          th APG
          th STP
          th BPG
          th FGA
          th FGM
          th FG%
          th 3PA
          th 3PM
          th 3P%
          th FTA
          th FTM
          th FT%
          th TOPG
      tbody
        tr 
          td v-for ="stut in player_stuts"  v-text ="stut"
          
            
  
  
    
= javascript_pack_tag "home/team_page"

app/views/home/team_reg.html.slim
#team_reg.mx-4
  h2 チーム登録
  = form_with(model: @team, url:team_create_path, local:true) do |f|
      p
        = f.label :チーム名, class: 'mr-2'
        = f.text_field :team_name
      = f.submit 'チーム登録', class: 'btn btn-primary'  
      
= javascript_pack_tag "home"
      