config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/new'
  get 'users/create'
  root to: 'home#home'
  get 'reg', to:'home#reg'
  post 'create', to:'home#create'
  get 'pregame', to:'game#pregame'
  get 'game', to:'game#game'
  post 'game_create', to:'game#game_create'
  resources :employees, only: [:index, :show]
  post 'game/check/:min/:sec' , to:'game#time'
  get 'start5', to:'game#start5'
  get 'game/getplayerInfo/:id', to:'game#player_info'
  post 'game/start5_confirm/:p1id/:p2id/:p3id/:p4id/:p5id', to:'game#start5_confirm'
  post 'game/finish/:score/:opp_score', to:'game#finish'
  post 'game/stuts_record/:p_id/:p_name/:playing_time/:a/:b/:c/:d/:e/:f/:g/:h/:i/:j/:k/:l/:m', to:'game#stuts_record'
  get 'home/box', to:'home#box'
  get 'home/player_select', to:'home#player_select'
  get 'home/player_edit', to:'home#player_edit'
  patch 'home/player_update' , to:'home#player_update'
  patch 'home/player_delete', to:'home#player_delete'
  resources :users, only: [:new, :create]
  get "/login" => "sessions#new"
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :teams do
    member do
      get 'details'
    end
    collection do
      get 'search'
    end
    resources :players
  end
  
end

app/views/layouts/_header.html.slim
#reg.sticky-top
  header#header
    nav.navbar.navbar-expand.navbar-light.bg-light.p-4
      = link_to 'score', root_path, class: "h1 text-muted mr-4"
      .collapse.navbar-collapse#navbarNavDropdown
        ul.navbar-nav.text-nowrap
          - if current_user
            
            li.nav-item
              = link_to "チーム登録",new_team_path , class: 'nav-link h4 mr-4'
            li.nav-item
              = link_to "試合",pregame_path , class: 'nav-link h4 mr-4'
            li.nav-item
            = link_to "ログアウト",logout_path,method: :post , class: 'nav-link h4 mr-4'
            = current_user.level
          - else
            li.nav-item
            = link_to "ログイン",login_path, class: 'nav-link h4 mr-4'
            li.nav-item
            = link_to "新規登録",new_user_path, class: 'nav-link h4 mr-4'
            

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Score
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon if defined? gon && gon.present?
    = stylesheet_pack_tag 'application', media: 'all' , 'data-turbolinks-track':  'reload'
    = javascript_pack_tag 'application'
    
  body
    == render 'layouts/header'
    div
     - flash.each do |name, msg|
        |  <div class="alert alert-
        = name
        | "> 
        = msg
    = yield
    